-- 智能投放 MVP 表结构
-- 目标库：sibebid；MySQL 5.7+/8.0；字符集 utf8mb4。
-- 执行前请先确认当前连接指向正确环境。应用不会自动建表。

USE `sibebid`;

CREATE TABLE IF NOT EXISTS `smart_placement_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_no` VARCHAR(32) NOT NULL COMMENT '投放任务编号',
  `opportunity_name` VARCHAR(200) NOT NULL COMMENT '投放机会名称',
  `opportunity_source` VARCHAR(32) NOT NULL COMMENT '机会来源：AUTO_ANALYSIS/MANUAL/MEETING',
  `analysis_rule_code` VARCHAR(64) DEFAULT NULL COMMENT '自动分析规则编号',
  `analysis_start_date` DATE NOT NULL COMMENT '分析开始日期',
  `analysis_end_date` DATE NOT NULL COMMENT '分析结束日期',

  `platform_code` VARCHAR(64) DEFAULT NULL COMMENT 'OTA平台编码',
  `platform_name` VARCHAR(100) NOT NULL COMMENT 'OTA平台名称',
  `site_code` VARCHAR(64) DEFAULT NULL COMMENT '站点编码',
  `site_name` VARCHAR(150) DEFAULT NULL COMMENT '站点名称',
  `airline_code` VARCHAR(32) NOT NULL COMMENT '航司二字码或业务航司编码',
  `departure_code` VARCHAR(32) DEFAULT NULL COMMENT '出发城市或机场编码',
  `arrival_code` VARCHAR(32) DEFAULT NULL COMMENT '到达城市或机场编码',
  `route_text` VARCHAR(300) DEFAULT NULL COMMENT '完整航程文本',
  `journey_type` VARCHAR(32) DEFAULT NULL COMMENT '航程类型',
  `flight_nos` VARCHAR(500) DEFAULT NULL COMMENT '适用航班号，多个用英文逗号分隔',
  `include_cabins` VARCHAR(500) DEFAULT NULL COMMENT '包含舱位，多个用英文逗号分隔',
  `exclude_cabins` VARCHAR(500) DEFAULT NULL COMMENT '排除舱位，多个用英文逗号分隔',
  `product_type` VARCHAR(150) DEFAULT NULL COMMENT '机票产品类型',

  `order_start_date` DATE DEFAULT NULL COMMENT '适用订单开始日期',
  `order_end_date` DATE DEFAULT NULL COMMENT '适用订单结束日期',
  `travel_start_date` DATE DEFAULT NULL COMMENT '适用起飞开始日期',
  `travel_end_date` DATE DEFAULT NULL COMMENT '适用起飞结束日期',
  `placement_method` VARCHAR(300) NOT NULL COMMENT '建议投放方式',
  `adjustment_value` DECIMAL(18,4) DEFAULT NULL COMMENT '建议价格调整值',
  `adjustment_unit` VARCHAR(32) DEFAULT NULL COMMENT '调整单位：CNY/PERCENT/OTHER',
  `suggested_effective_start` DATETIME DEFAULT NULL COMMENT '建议生效时间',
  `suggested_effective_end` DATETIME DEFAULT NULL COMMENT '建议失效时间',

  `historical_ticket_count` BIGINT DEFAULT NULL COMMENT '历史票数',
  `historical_segment_count` BIGINT DEFAULT NULL COMMENT '历史航段数',
  `historical_profit_cny` DECIMAL(20,4) DEFAULT NULL COMMENT '历史业务估算利润CNY',
  `estimated_month_ticket_count` BIGINT DEFAULT NULL COMMENT '预估月票数',
  `estimated_month_profit_cny` DECIMAL(20,4) DEFAULT NULL COMMENT '预估月利润CNY',
  `analysis_conclusion` TEXT NOT NULL COMMENT '数据分析结论',
  `risk_note` TEXT DEFAULT NULL COMMENT '风险提示',
  `priority` VARCHAR(16) NOT NULL DEFAULT 'MEDIUM' COMMENT '优先级：HIGH/MEDIUM/LOW',
  `expected_complete_at` DATETIME NOT NULL COMMENT '期望完成时间',

  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PENDING_DATA_REVIEW/PENDING_POLICY_REVIEW/CLAIMABLE/IN_PROGRESS/MONITORING/FAILED/REJECTED/CLOSED/ENDED',
  `current_assignee_id` BIGINT DEFAULT NULL COMMENT '当前认领人用户ID',
  `current_assignee_name` VARCHAR(100) DEFAULT NULL COMMENT '当前认领人姓名快照',
  `submitted_at` DATETIME DEFAULT NULL COMMENT '提交审核时间',
  `data_reviewed_at` DATETIME DEFAULT NULL COMMENT '数据经理审核完成时间',
  `policy_reviewed_at` DATETIME DEFAULT NULL COMMENT '政策经理审核完成时间',
  `claimed_at` DATETIME DEFAULT NULL COMMENT '认领时间',
  `monitoring_started_at` DATETIME DEFAULT NULL COMMENT '订单匹配监控开始时间',
  `closed_at` DATETIME DEFAULT NULL COMMENT '任务关闭或结束时间',
  `version_no` INT NOT NULL DEFAULT 1 COMMENT '乐观锁版本',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  `created_by_id` BIGINT NOT NULL COMMENT '创建人用户ID',
  `created_by_name` VARCHAR(100) NOT NULL COMMENT '创建人姓名快照',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by_id` BIGINT NOT NULL COMMENT '最后更新人用户ID',
  `updated_by_name` VARCHAR(100) NOT NULL COMMENT '最后更新人姓名快照',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_smart_placement_task_no` (`task_no`),
  KEY `idx_spt_status_priority_due` (`status`, `priority`, `expected_complete_at`),
  KEY `idx_spt_assignee_status` (`current_assignee_id`, `status`),
  KEY `idx_spt_platform_site` (`platform_name`, `site_name`),
  KEY `idx_spt_airline_route` (`airline_code`, `departure_code`, `arrival_code`),
  KEY `idx_spt_analysis_period` (`analysis_start_date`, `analysis_end_date`),
  KEY `idx_spt_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能投放任务主表';

CREATE TABLE IF NOT EXISTS `smart_placement_review` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` BIGINT UNSIGNED NOT NULL COMMENT '投放任务ID',
  `review_stage` VARCHAR(32) NOT NULL COMMENT 'DATA_MANAGER/POLICY_MANAGER',
  `review_result` VARCHAR(16) NOT NULL COMMENT 'APPROVED/RETURNED/REJECTED',
  `review_comment` TEXT DEFAULT NULL COMMENT '审核意见',
  `data_metric_confirmed` TINYINT(1) DEFAULT NULL COMMENT '数据口径已确认',
  `sample_sufficient` TINYINT(1) DEFAULT NULL COMMENT '样本充分性已确认',
  `estimated_value_confirmed` TINYINT(1) DEFAULT NULL COMMENT '预估价值已确认',
  `policy_executable_level` VARCHAR(32) DEFAULT NULL COMMENT 'EXECUTABLE/CONDITIONAL/NOT_EXECUTABLE',
  `risk_level` VARCHAR(16) DEFAULT NULL COMMENT 'HIGH/MEDIUM/LOW',
  `risk_control_requirement` TEXT DEFAULT NULL COMMENT '风险控制要求',
  `claim_scope` VARCHAR(500) DEFAULT NULL COMMENT '允许认领的人员或小组说明',
  `adjusted_priority` VARCHAR(16) DEFAULT NULL COMMENT '审核调整后的优先级',
  `adjusted_complete_at` DATETIME DEFAULT NULL COMMENT '审核调整后的完成时间',
  `reviewer_id` BIGINT NOT NULL COMMENT '审核人用户ID',
  `reviewer_name` VARCHAR(100) NOT NULL COMMENT '审核人姓名快照',
  `reviewer_role_snapshot` VARCHAR(64) NOT NULL COMMENT '审核角色快照',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '审核时间',
  PRIMARY KEY (`id`),
  KEY `idx_spr_task_stage_time` (`task_id`, `review_stage`, `created_at`),
  KEY `idx_spr_reviewer_time` (`reviewer_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能投放审核记录';

CREATE TABLE IF NOT EXISTS `smart_placement_execution` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` BIGINT UNSIGNED NOT NULL COMMENT '投放任务ID',
  `attempt_no` INT NOT NULL COMMENT '本任务第几次执行',
  `execution_result` VARCHAR(16) NOT NULL COMMENT 'SUCCESS/FAILED',
  `external_policy_id` VARCHAR(128) DEFAULT NULL COMMENT '外部政策ID，成功时必填',
  `external_policy_name` VARCHAR(200) DEFAULT NULL COMMENT '外部政策名称',
  `actual_placement_at` DATETIME DEFAULT NULL COMMENT '实际投放时间',
  `effective_start_at` DATETIME DEFAULT NULL COMMENT '政策生效时间',
  `effective_end_at` DATETIME DEFAULT NULL COMMENT '政策失效时间',
  `platform_code` VARCHAR(64) DEFAULT NULL COMMENT '实际平台编码',
  `platform_name` VARCHAR(100) DEFAULT NULL COMMENT '实际平台名称',
  `site_code` VARCHAR(64) DEFAULT NULL COMMENT '实际站点编码',
  `site_name` VARCHAR(150) DEFAULT NULL COMMENT '实际站点名称',
  `airline_code` VARCHAR(32) DEFAULT NULL COMMENT '实际航司',
  `departure_code` VARCHAR(32) DEFAULT NULL COMMENT '实际出发地',
  `arrival_code` VARCHAR(32) DEFAULT NULL COMMENT '实际到达地',
  `route_text` VARCHAR(300) DEFAULT NULL COMMENT '实际航程',
  `flight_nos` VARCHAR(500) DEFAULT NULL COMMENT '实际航班号',
  `include_cabins` VARCHAR(500) DEFAULT NULL COMMENT '实际包含舱位',
  `exclude_cabins` VARCHAR(500) DEFAULT NULL COMMENT '实际排除舱位',
  `product_type` VARCHAR(150) DEFAULT NULL COMMENT '实际机票产品类型',
  `adjustment_value` DECIMAL(18,4) DEFAULT NULL COMMENT '实际价格调整值',
  `adjustment_unit` VARCHAR(32) DEFAULT NULL COMMENT '实际调整单位',
  `placement_channel` VARCHAR(100) DEFAULT NULL COMMENT '外部投放渠道',
  `proof_url` VARCHAR(500) DEFAULT NULL COMMENT '投放凭证地址',
  `execution_note` TEXT DEFAULT NULL COMMENT '执行说明',
  `failure_type` VARCHAR(64) DEFAULT NULL COMMENT '失败类型',
  `failure_reason` TEXT DEFAULT NULL COMMENT '失败原因',
  `retry_required` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否重新执行',
  `next_handle_at` DATETIME DEFAULT NULL COMMENT '下次处理时间',
  `operator_id` BIGINT NOT NULL COMMENT '登记人用户ID',
  `operator_name` VARCHAR(100) NOT NULL COMMENT '登记人姓名快照',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登记时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_spe_task_attempt` (`task_id`, `attempt_no`),
  KEY `idx_spe_policy_id` (`external_policy_id`),
  KEY `idx_spe_effective_period` (`effective_start_at`, `effective_end_at`),
  KEY `idx_spe_result_time` (`execution_result`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能投放执行记录';

CREATE TABLE IF NOT EXISTS `smart_placement_order_match` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `match_no` VARCHAR(40) NOT NULL COMMENT '匹配记录编号',
  `task_id` BIGINT UNSIGNED NOT NULL COMMENT '投放任务ID',
  `execution_id` BIGINT UNSIGNED NOT NULL COMMENT '命中的执行记录ID',
  `external_policy_id` VARCHAR(128) NOT NULL COMMENT '命中的外部政策ID',
  `internal_order_id` VARCHAR(100) DEFAULT NULL COMMENT '订单内部ID',
  `ota_order_no` VARCHAR(150) NOT NULL COMMENT 'OTA订单号',
  `ticket_no` VARCHAR(100) DEFAULT NULL COMMENT '出票票号',
  `passenger_name` VARCHAR(200) DEFAULT NULL COMMENT '乘客姓名',
  `platform_name` VARCHAR(100) DEFAULT NULL COMMENT '平台名称',
  `site_name` VARCHAR(150) DEFAULT NULL COMMENT '站点名称',
  `airline_code` VARCHAR(32) DEFAULT NULL COMMENT '航司',
  `departure_code` VARCHAR(32) DEFAULT NULL COMMENT '出发地',
  `arrival_code` VARCHAR(32) DEFAULT NULL COMMENT '到达地',
  `route_text` VARCHAR(300) DEFAULT NULL COMMENT '航程',
  `flight_nos` VARCHAR(500) DEFAULT NULL COMMENT '航班号',
  `cabin_codes` VARCHAR(500) DEFAULT NULL COMMENT '实际舱位',
  `product_type` VARCHAR(150) DEFAULT NULL COMMENT '机票产品类型',
  `order_time` DATETIME DEFAULT NULL COMMENT '进单时间',
  `ticket_time` DATETIME DEFAULT NULL COMMENT '出票时间',
  `departure_time` DATETIME DEFAULT NULL COMMENT '首段起飞时间',
  `ticket_count` BIGINT DEFAULT NULL COMMENT '票数',
  `segment_count` BIGINT DEFAULT NULL COMMENT '航段数',
  `order_amount_cny` DECIMAL(20,4) DEFAULT NULL COMMENT '订单金额CNY',
  `estimated_profit_cny` DECIMAL(20,4) DEFAULT NULL COMMENT '业务估算利润CNY',
  `match_detail` TEXT DEFAULT NULL COMMENT '命中条件说明',
  `match_version` VARCHAR(32) NOT NULL DEFAULT 'v1' COMMENT '匹配规则版本',
  `is_duplicate_match` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否重复命中',
  `matched_at` DATETIME NOT NULL COMMENT '匹配时间',
  `message_channel` VARCHAR(32) DEFAULT NULL COMMENT '消息渠道',
  `message_target` VARCHAR(200) DEFAULT NULL COMMENT '接收群或目标',
  `message_status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/SENT/FAILED',
  `message_sent_at` DATETIME DEFAULT NULL COMMENT '消息发送成功时间',
  `message_external_id` VARCHAR(200) DEFAULT NULL COMMENT '外部消息ID',
  `message_attempt_count` INT NOT NULL DEFAULT 0 COMMENT '消息发送次数',
  `message_error` VARCHAR(500) DEFAULT NULL COMMENT '最后发送错误',
  `attention_status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/IN_PROGRESS/COMPLETED/NO_ACTION/ESCALATED',
  `attention_owner_id` BIGINT DEFAULT NULL COMMENT '关注负责人用户ID',
  `attention_owner_name` VARCHAR(100) DEFAULT NULL COMMENT '关注负责人姓名快照',
  `first_response_at` DATETIME DEFAULT NULL COMMENT '首次确认关注时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '处理完成时间',
  `resolution_code` VARCHAR(64) DEFAULT NULL COMMENT '处理结果编码',
  `resolution_note` TEXT DEFAULT NULL COMMENT '处理说明',
  `escalation_count` INT NOT NULL DEFAULT 0 COMMENT '升级次数',
  `last_reminded_at` DATETIME DEFAULT NULL COMMENT '最后催办时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_spom_match_no` (`match_no`),
  KEY `idx_spom_task_match_time` (`task_id`, `matched_at`),
  KEY `idx_spom_policy_match_time` (`external_policy_id`, `matched_at`),
  KEY `idx_spom_attention_time` (`attention_status`, `matched_at`),
  KEY `idx_spom_owner_status` (`attention_owner_id`, `attention_status`),
  KEY `idx_spom_order_ticket` (`ota_order_no`, `ticket_no`),
  KEY `idx_spom_platform_airline` (`platform_name`, `airline_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能投放订单匹配与关注记录';

CREATE TABLE IF NOT EXISTS `smart_placement_operation_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_id` BIGINT UNSIGNED NOT NULL COMMENT '投放任务ID',
  `match_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '订单匹配记录ID',
  `action_code` VARCHAR(64) NOT NULL COMMENT 'CREATE/SUBMIT/REVIEW/CLAIM/EXECUTE/ATTENTION等',
  `from_status` VARCHAR(32) DEFAULT NULL COMMENT '操作前状态',
  `to_status` VARCHAR(32) DEFAULT NULL COMMENT '操作后状态',
  `operator_id` BIGINT DEFAULT NULL COMMENT '操作人用户ID；系统任务可为空',
  `operator_name` VARCHAR(100) NOT NULL COMMENT '操作人姓名或SYSTEM',
  `operator_role_snapshot` VARCHAR(64) DEFAULT NULL COMMENT '操作角色快照',
  `operation_note` VARCHAR(1000) DEFAULT NULL COMMENT '操作说明',
  `detail_json` TEXT DEFAULT NULL COMMENT '结构化变更详情JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  PRIMARY KEY (`id`),
  KEY `idx_spol_task_time` (`task_id`, `created_at`),
  KEY `idx_spol_match_time` (`match_id`, `created_at`),
  KEY `idx_spol_operator_time` (`operator_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能投放操作审计日志';
