USE `sibebid`;

CREATE TABLE `sys_user_page_visit` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `visit_id` CHAR(32) NOT NULL COMMENT '一次页面访问的前端UUID（去横线）',
  `user_id` INT NOT NULL COMMENT 'sys_user.id，由后端登录会话写入',
  `session_id` BIGINT UNSIGNED NULL COMMENT 'auth_session.id',
  `user_role_snapshot` VARCHAR(20) NOT NULL COMMENT '访问发生时的角色快照：admin/user',
  `module_code` VARCHAR(100) NULL COMMENT '模块稳定编码',
  `page_code` VARCHAR(100) NOT NULL COMMENT '页面稳定编码，对应前端路由名',
  `route_path` VARCHAR(255) NOT NULL COMMENT '不含查询参数的路由路径',
  `page_title` VARCHAR(100) NOT NULL COMMENT '访问时页面标题快照',
  `referrer_page_code` VARCHAR(100) NULL COMMENT '上一个站内页面编码',
  `entered_at` DATETIME(3) NOT NULL COMMENT '进入时间，UTC',
  `last_active_at` DATETIME(3) NOT NULL COMMENT '最后活跃时间，UTC',
  `left_at` DATETIME(3) NULL COMMENT '可确认的离开时间，UTC',
  `active_duration_ms` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '页面有效活跃时长毫秒',
  `load_duration_ms` INT UNSIGNED NULL COMMENT '页面切换完成耗时毫秒',
  `action_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '该次访问内有效操作数',
  `exit_type` VARCHAR(32) NULL COMMENT 'route_change/page_hidden/unload/logout/expired',
  `viewport_width` SMALLINT UNSIGNED NULL COMMENT '浏览器可视区宽度',
  `viewport_height` SMALLINT UNSIGNED NULL COMMENT '浏览器可视区高度',
  `device_type` VARCHAR(20) NOT NULL DEFAULT 'desktop' COMMENT 'desktop/tablet/mobile',
  `app_version` VARCHAR(64) NULL COMMENT '前端版本或Git提交号',
  `created_at` DATETIME(3) NOT NULL COMMENT '记录创建时间，UTC',
  `updated_at` DATETIME(3) NOT NULL COMMENT '记录更新时间，UTC',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_page_visit_visit_id` (`visit_id`),
  KEY `idx_user_page_visit_user_time` (`user_id`, `entered_at`),
  KEY `idx_user_page_visit_page_time` (`page_code`, `entered_at`),
  KEY `idx_user_page_visit_session_time` (`session_id`, `entered_at`),
  KEY `idx_user_page_visit_referrer_time` (`referrer_page_code`, `entered_at`),
  KEY `idx_user_page_visit_entered_at` (`entered_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据中心用户页面访问事实表';

CREATE TABLE `sys_user_behavior_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `event_id` CHAR(32) NOT NULL COMMENT '行为事件前端UUID（去横线），用于幂等',
  `visit_id` CHAR(32) NOT NULL COMMENT '关联sys_user_page_visit.visit_id',
  `user_id` INT NOT NULL COMMENT 'sys_user.id，由后端登录会话写入',
  `session_id` BIGINT UNSIGNED NULL COMMENT 'auth_session.id',
  `user_role_snapshot` VARCHAR(20) NOT NULL COMMENT '行为发生时的角色快照：admin/user',
  `module_code` VARCHAR(100) NULL COMMENT '模块稳定编码',
  `page_code` VARCHAR(100) NOT NULL COMMENT '页面稳定编码',
  `route_path` VARCHAR(255) NOT NULL COMMENT '不含查询参数的路由路径',
  `event_type` VARCHAR(40) NOT NULL COMMENT '点击、查询、筛选、下钻、错误等事件类型',
  `element_code` VARCHAR(100) NULL COMMENT '控件或接口稳定编码',
  `element_name` VARCHAR(100) NULL COMMENT '用户可见控件名称快照',
  `result_status` VARCHAR(20) NOT NULL DEFAULT 'unknown' COMMENT 'success/failed/cancelled/empty/unknown',
  `duration_ms` INT UNSIGNED NULL COMMENT '查询或操作耗时毫秒',
  `error_code` VARCHAR(100) NULL COMMENT '脱敏后的错误编码',
  `request_id` VARCHAR(64) NULL COMMENT '关联后端日志的请求编号',
  `context_json` JSON NULL COMMENT '白名单上下文，不保存订单、票号、姓名和筛选值',
  `event_version` SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '埋点口径版本',
  `occurred_at` DATETIME(3) NOT NULL COMMENT '客户端事件时间，UTC',
  `received_at` DATETIME(3) NOT NULL COMMENT '服务端接收时间，UTC',
  `app_version` VARCHAR(64) NULL COMMENT '前端版本或Git提交号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_behavior_event_event_id` (`event_id`),
  KEY `idx_user_behavior_event_visit_time` (`visit_id`, `occurred_at`),
  KEY `idx_user_behavior_event_user_time` (`user_id`, `occurred_at`),
  KEY `idx_user_behavior_event_page_type_time` (`page_code`, `event_type`, `occurred_at`),
  KEY `idx_user_behavior_event_type_time` (`event_type`, `occurred_at`),
  KEY `idx_user_behavior_event_request_id` (`request_id`),
  KEY `idx_user_behavior_event_occurred_at` (`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据中心用户关键行为事件事实表';

