from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RiskUploadDefinition:
    key: str
    label: str
    target_table: str
    default_sheet: str
    source_to_target: tuple[tuple[str, str], ...]
    partition_date_required: bool = False

    @property
    def write_mode(self) -> str:
        return "按出票票号增量更新；0利润删除"


ISSUE_COLUMNS = (
    ("日期", "business_date"),
    ("OTA平台名称", "ota_cname"),
    ("站点名称", "ota_site_cname"),
    ("业务部门名称", "org_cname"),
    ("出票日期", "issue_date"),
    ("OTA订单号", "ota_order_no"),
    ("关联订单号", "relation_order_no"),
    ("出票票号", "issue_ticket_no"),
    ("盈亏原因", "profit_reason_type"),
    ("利润备注", "profit_remark"),
    ("风控核实", "risk_verify_result"),
    ("备注", "remark"),
    ("业务单号", "order_no"),
    ("出票编码", "issue_pnr_no"),
    ("航程类型", "flight_way"),
    ("航程", "air_route"),
    ("航司", "marketing_airline"),
    ("航班号", "flight_no"),
    ("首段日期", "first_segment_date"),
    ("航班日期", "flight_datetime"),
    ("舱位", "cabin"),
    ("实际舱位", "actual_cabin"),
    ("航段数", "segment_num"),
    ("航段奖励段数", "reward_segment_num"),
    ("销售币种", "sale_currency"),
    ("应收原币金额", "receivable_org_amount"),
    ("实收原币金额", "received_org_amount"),
    ("应收CNY金额", "receivable_cny_amount"),
    ("实收CNY金额", "received_cny_amount"),
    ("佣金CNY金额", "sale_commission_cny_amount"),
    ("销售汇兑损益", "sale_fx_gain_loss_cny"),
    ("应收预估汇率", "receivable_estimated_exchange_rate"),
    ("实际收款汇率", "actual_receipt_exchange_rate"),
    ("实际收款日期", "actual_receipt_date"),
    ("收款账号名称", "receipt_account_name"),
    ("供应商名称", "supplier_cname"),
    ("采购币种", "purchase_currency"),
    ("票面原币金额", "ticket_price_org_amount"),
    ("税额原币金额", "tax_org_amount"),
    ("手续费原币金额", "fee_org_amount"),
    ("供应商前返原币金额", "supplier_front_rebate_org_amount"),
    ("供应商后返原币金额", "supplier_back_rebate_org_amount"),
    ("应付原币金额", "payable_org_amount"),
    ("实付原币金额", "paid_org_amount"),
    ("应付CNY金额", "payable_cny_amount"),
    ("实付CNY金额", "paid_cny_amount"),
    ("应付预估汇率", "payable_estimated_exchange_rate"),
    ("实际付款汇率", "actual_payment_exchange_rate"),
    ("采购汇兑损益", "purchase_fx_gain_loss_cny"),
    ("实际付款时间", "actual_payment_time"),
    ("付款账号名称", "payment_account_name"),
    ("航段奖励CNY金额", "segment_reward_cny_amount"),
    ("支付卡返CNY", "payment_card_rebate_cny_amount"),
    ("供应商后返CNY金额", "supplier_back_rebate_cny_amount"),
    ("利润结算日期", "profit_settlement_date"),
    ("预估利润(公式)", "estimated_profit_cny"),
    ("实际利润(推算)", "actual_profit_cny"),
    ("政策员", "policy_operator"),
    ("过单员", "order_confirm_operator"),
    ("出票员", "issue_operator"),
    ("业绩分类", "performance_category"),
    ("业务合并", "merge_business_flag"),
    ("合并业务类型", "merge_business_type"),
    ("订单标识", "order_tag"),
    ("废票状态", "void_status"),
    ("应收对账状态", "receivable_reconcile_status"),
    ("应付对账状态", "payable_reconcile_status"),
    ("应收账单编号", "receivable_bill_no"),
    ("应付账单编号", "payable_bill_no"),
    ("公司名称", "company_cname"),
    ("订位GDS", "book_gds_channel"),
    ("订位PCC", "book_office_no"),
    ("订单乘客id", "order_passenger_id"),
    ("数据来源id", "data_source_id"),
    ("数据来源obj", "data_source_obj"),
    ("乘客名称", "passenger_name"),
    ("票数", "ticket_num"),
    ("月份", "month_name"),
    ("正确原因", "correct_reason"),
    ("订单来源", "order_source"),
    ("产品类型", "product_type"),
    ("计入差错", "error_included_flag"),
    ("备注【原始】", "original_remark"),
)


REFUND_COLUMNS = (
    ("日期", "stat_date"),
    ("OTA平台名称", "ota_cname"),
    ("站点名称", "ota_site_cname"),
    ("业务部门名称", "org_cname"),
    ("OTA订单号", "ota_order_no"),
    ("关联订单号", "relation_order_no"),
    ("出票票号", "issue_ticket_no"),
    ("出票编码", "issue_pnr_no"),
    ("退票单号", "refund_order_no"),
    ("利润备注", "profit_remark"),
    ("核实", "verify_result"),
    ("备注", "remark"),
    ("出票日期", "issue_date"),
    ("进单日期", "apply_date"),
    ("航程", "air_route"),
    ("航司", "marketing_airline"),
    ("航班号", "flight_no"),
    ("首段日期", "first_segment_date"),
    ("航班日期", "flight_datetime"),
    ("舱位", "cabin"),
    ("实际舱位", "actual_cabin"),
    ("航段奖励段数", "reward_segment_num"),
    ("销售币种", "sale_currency"),
    ("应退原币金额", "refund_due_org_amount"),
    ("实退原币金额", "refund_actual_org_amount"),
    ("应退CNY金额", "refund_due_cny_amount"),
    ("实退CNY金额", "refund_actual_cny_amount"),
    ("佣金CNY金额", "sale_commission_cny_amount"),
    ("退款时间", "refund_time"),
    ("退款账号", "refund_account_name"),
    ("应退预估汇率", "refund_estimated_exchange_rate"),
    ("实际退款汇率", "actual_refund_exchange_rate"),
    ("供应商名称", "supplier_cname"),
    ("采购币种", "purchase_currency"),
    ("手续费原币金额", "refund_fee_org_amount"),
    ("应收退款原币", "supplier_refund_receivable_org_amount"),
    ("实收退款原币", "supplier_refund_received_org_amount"),
    ("应收退款CNY", "supplier_refund_receivable_cny_amount"),
    ("实收退款CNY", "supplier_refund_received_cny_amount"),
    ("应收退款汇率", "supplier_refund_receivable_rate"),
    ("实收退款汇率", "supplier_refund_received_rate"),
    ("实收退款汇兑损益", "supplier_refund_fx_gain_loss_cny"),
    ("实收退款时间", "supplier_refund_received_time"),
    ("实收退款账号名称", "supplier_refund_account_name"),
    ("航段奖励CNY金额", "segment_reward_cny_amount"),
    ("支付卡返CNY", "payment_card_rebate_cny_amount"),
    ("供应商后返CNY金额", "supplier_back_rebate_cny_amount"),
    ("利润结算日期", "profit_settlement_date"),
    ("预估利润(公式)", "estimated_profit_cny"),
    ("实际利润(推算)", "actual_profit_cny"),
    ("政策员", "policy_operator"),
    ("操作员", "refund_operator"),
    ("业绩分类", "performance_category"),
    ("业务合并", "merge_business_flag"),
    ("合并业务类型", "merge_business_type"),
    ("订单标识", "order_tag"),
    ("废票状态", "void_status"),
    ("应收对账状态", "receivable_reconcile_status"),
    ("应付对账状态", "payable_reconcile_status"),
    ("应收账单编号", "receivable_bill_no"),
    ("应付账单编号", "payable_bill_no"),
    ("公司名称", "company_cname"),
    ("订位GDS", "book_gds_channel"),
    ("订位PCC", "book_office_no"),
    ("业务日期", "business_date"),
    ("订单内部id", "order_id"),
    ("订单乘客id", "order_passenger_id"),
    ("数据来源id", "data_source_id"),
    ("数据来源obj", "data_source_obj"),
    ("乘客名称", "passenger_name"),
    ("应收业务状态", "receivable_business_status"),
    ("应付业务状态", "payable_business_status"),
    ("票数", "ticket_num"),
    ("月份", "month_name"),
)


CHANGE_COLUMNS = (
    ("日期", "stat_date"),
    ("OTA平台名称", "ota_cname"),
    ("站点名称", "ota_site_cname"),
    ("业务部门名称", "org_cname"),
    ("OTA订单号", "ota_order_no"),
    ("关联订单号", "relation_order_no"),
    ("出票票号", "issue_ticket_no"),
    ("出票编码", "issue_pnr_no"),
    ("改签单号", "change_order_no"),
    ("利润备注", "profit_remark"),
    ("核实", "verify_result"),
    ("备注", "remark"),
    ("出票日期", "issue_date"),
    ("进单日期", "apply_date"),
    ("航程", "air_route"),
    ("航司", "marketing_airline"),
    ("航班号", "flight_no"),
    ("首段日期", "first_segment_date"),
    ("航班日期", "flight_datetime"),
    ("舱位", "cabin"),
    ("实际舱位", "actual_cabin"),
    ("航段奖励段数", "reward_segment_num"),
    ("应收原币金额", "receivable_org_amount"),
    ("实收原币金额", "received_org_amount"),
    ("应收CNY金额", "receivable_cny_amount"),
    ("实收CNY金额", "received_cny_amount"),
    ("应收预估汇率", "receivable_estimated_exchange_rate"),
    ("实际收款汇率", "actual_receipt_exchange_rate"),
    ("销售汇兑损益", "sale_fx_gain_loss_cny"),
    ("实际收款日期", "actual_receipt_date"),
    ("收款账号名称", "receipt_account_name"),
    ("供应商名称", "supplier_cname"),
    ("采购币种", "purchase_currency"),
    ("应付原币金额", "payable_org_amount"),
    ("实付原币金额", "paid_org_amount"),
    ("应付CNY金额", "payable_cny_amount"),
    ("实付CNY金额", "paid_cny_amount"),
    ("应付预估汇率", "payable_estimated_exchange_rate"),
    ("实际付款汇率", "actual_payment_exchange_rate"),
    ("采购汇兑损益", "purchase_fx_gain_loss_cny"),
    ("实际付款时间", "actual_payment_time"),
    ("付款账号名称", "payment_account_name"),
    ("航段奖励CNY金额", "segment_reward_cny_amount"),
    ("虚拟卡返CNY", "payment_card_rebate_cny_amount"),
    ("利润结算日期", "profit_settlement_date"),
    ("预估利润", "estimated_profit_cny"),
    ("实际利润(推算)", "actual_profit_cny"),
    ("政策员", "policy_operator"),
    ("操作员", "change_operator"),
    ("业绩分类", "performance_category"),
    ("业务合并", "merge_business_flag"),
    ("合并业务类型", "merge_business_type"),
    ("订单标识", "order_tag"),
    ("废票状态", "void_status"),
    ("应收对账状态", "receivable_reconcile_status"),
    ("应付对账状态", "payable_reconcile_status"),
    ("应收账单编号", "receivable_bill_no"),
    ("应付账单编号", "payable_bill_no"),
    ("公司名称", "company_cname"),
    ("订单内部id", "order_id"),
    ("订单乘客id", "order_passenger_id"),
    ("数据来源id", "data_source_id"),
    ("数据来源obj", "data_source_obj"),
    ("乘客名称", "passenger_name"),
    ("票数", "ticket_num"),
    ("月份", "month_name"),
)


RISK_UPLOAD_DEFINITIONS = {
    "issue": RiskUploadDefinition(
        key="issue",
        label="出票",
        target_table="lywz.dwd_order_issue_profit_reconcile_year",
        default_sheet="2026年1-8月明细",
        source_to_target=ISSUE_COLUMNS,
    ),
    "refund": RiskUploadDefinition(
        key="refund",
        label="退票",
        target_table="lywz.dwd_order_refund_profit_reconcile_year",
        default_sheet="2026年明细表格",
        source_to_target=REFUND_COLUMNS,
    ),
    "change": RiskUploadDefinition(
        key="change",
        label="改签",
        target_table="lywz.dwd_order_change_profit_reconcile_year",
        default_sheet="月度明细",
        source_to_target=CHANGE_COLUMNS,
    ),
}
